 DROP DATABASE IF EXISTS ozono;

CREATE DATABASE ozono;

USE ozono;

CREATE TABLE products(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name TEXT NOT NULL,
    description_html TEXT NOT NULL,
    image_url TEXT NOT NULL,
    video_html TEXT NOT NULL
); 

 INSERT INTO products(
     name, description_html, image_url, video_html
 ) VALUES
 ('Modelo Gota en Acero Inoxidable', '                                <ul>\r\n                                    <li>Hecho en Acero Inoxidable (18-8).</li>\r\n                                    <li>Caño Fijo.</li>\r\n                                    <li>Medidas: 31cm. x 21cm. x 14 cm.</li>\r\n                                </ul>', 'modelo_gota.png', '                                <div>\r\n                                    <iframe width=\"350\" height=\"180\" src=\"https://www.youtube.com/embed/oCiPeNQmkzQ\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\r\n                                </div>'),
('Modelo Alargado en Acero Inoxidable', '                                <ul>\r\n                                    <li>Hecho en Acero Inoxidable (18-8).</li>\r\n                                    <li>Caño Giratorio.</li>\r\n                                    <li>Medidas: 31cm. x 15cm. x 9 cm.</li>\r\n                                </ul>  ', 'modelo_alargado.png', '                                <div>\r\n                                    <iframe width=\"350\" height=\"180\" src=\"https://www.youtube.com/embed/oCiPeNQmkzQ\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\r\n                                </div>'),
('Modelo Mini en Acrílico - ABS', '                                <ul>\r\n                                    <li>Hecho en Acrílico - ABS.</li>\r\n                                    <li>Caño Giratorio.</li>\r\n                                    <li>Medidas: 22cm. x 16cm. x 9 cm.</li>\r\n                                </ul>  ', 'modelo_mini.png', '                                <div>\r\n                                    <iframe width=\"350\" height=\"180\" src=\"https://www.youtube.com/embed/oCiPeNQmkzQ\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\r\n                                </div>'),
('Modelo Aerodinámico en Acrílico - ABS', '                                <ul>\r\n                                    <li>Hecho en Acrílico - ABS.</li>\r\n                                    <li>Caño Fijo.</li>\r\n                                    <li>Medidas: 31cm. x 20cm. x 15 cm.</li>\r\n                                </ul>   ', 'modelo_aerodinamico.png', '                                <div>\r\n                                    <iframe width=\"350\" height=\"180\" src=\"https://www.youtube.com/embed/oCiPeNQmkzQ\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\r\n                                </div>'),
('Ducha aséptica con Ozono', '                                <ul>\r\n                                    <li class=\"li_descripcion\">\r\n                                        Es ideal en el campo de la higiene y la belleza, ya que el agua ozonizada elimina \r\n                                        problemas de caspa, caída del cabello, irritaciones de la piel, sarpullidos, espinillas, \r\n                                        residuos del maquillaje, etc. Tiene gran aplicación en la higiene íntima, por su poder \r\n                                        germinicida, desodorizante y desinfectante. Estos beneficios se obtienen debido a que el \r\n                                        oxígeno adicional presente en el agua actúa directamente sobre los poros y la epidermis \r\n                                        eliminando las toxinas. Se utiliza también como enjuague bucal para prevenir las caries.\r\n                                        Para usar sólo con agua fría. \r\n                                    </li>\r\n                                    <li>Hecho en Acrílico - ABS</li>\r\n                                    <li>Con filtro de carbón activado.</li>\r\n                                    <li>Uso sólo con agua fría.</li>\r\n                                    <li>Medidas: 37cm. x 33cm. x 17cm.</li>\r\n                                </ul>', 'ducha_ozono.png', '                                <div>\r\n                                    <iframe width=\"350\" height=\"180\" src=\"https://www.youtube.com/embed/oCiPeNQmkzQ\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\r\n                                </div>'),
('Purificador de Aire Doméstico', '                                <ul>\r\n                                    <li class=\"li_descripcion\">\r\n                                        El peligro de propagación de enfermedades por médio del aire aumenta cuando varias \r\n                                        personas se mueven en ambientes mal ventilados. El equipo ozonizador elimina malos olores \r\n                                        y purifica el ambiente saturado por toxinas dejando el aire saludables y fresco, al realizar \r\n                                        una acción antimicrobiana que elimina toda clase de bacterias, virus, microorganismos patógenos \r\n                                        causantes de enfermedades como bronquitis, alergias y procesos asmáticos. \r\n                                    </li>\r\n                                    <li>Hecho en Acrílico - ABS</li>\r\n                                    <li>Funcionamiento Con Temporizador.</li>\r\n                                    <li>Apto para todo tipo de ambiente : 30 m<sup>3</sup> aprox</li>\r\n                                    <li>Portátil</li>\r\n                                    <li>Medidas: 29cm. x 19cm. x 10cm.</li>\r\n                                </ul>', 'purificador_aire_domestico.png', '                                <div>\r\n                                    <iframe width=\"350\" height=\"180\" src=\"https://www.youtube.com/embed/oCiPeNQmkzQ\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\r\n                                </div>'),
('Purificador de Agua Industrial', '                                <ul>\r\n                                    <li>Con 2 filtros de 2.75\"x20\" (Para Sedimentación y carbón Activo).</li>\r\n                                    <li>Hecho en Acrílico Thermo Conformado.</li>\r\n                                    <li>Capacidad de Ozonización: 100mg/h.</li>\r\n                                    <li>Capacidad Máxima de Agua: 500Lts/h.</li>\r\n                                    <li>Voltaje: 220v.</li>\r\n                                </ul>  ', 'purificador_agua_industrial.png', '                                <div>\r\n                                    <iframe width=\"350\" height=\"180\" src=\"https://www.youtube.com/embed/oCiPeNQmkzQ\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\r\n                                </div>');
 -- ("Filtro Plus Americano", "<div>Descripción <h1>8</h1></div>", "filtro_purificador.png", "<div>video <h1>8</h1></div>");
